### ISSUE TITLE
Facebook does not seem to pickup tags

### ISSUE THREAD

**Issue by cbanbury** [tomwasd/flow-router-seo#6]
I'm not sure if this is an issue or I'm just not implementing this properly. 

Have a blank `home.html` template and trying the following: 

```
Template.home.onCreated(function() {
  SEO.set({
    meta: {
        'property="og:type"': 'website',
        'property="og:title"': 'Some example title',
        'property="og:description"': 'An example description'
    }
  });
});
```

Have checked on the page and the tags appear to be loading, but Facebook is not picking them up. Any Ideas? 

Thanks

**Comment by tomwasd** [comment]
Hi @cbanbury,

Do you have the spiderable package installed and phantomjs set up?

I'm not sure Facebook will pick it up without those two.

**Comment by cbanbury** [comment]
Thanks @tomwasd, 

Looks like I skimmed over the spiderable docs too quickly. Will have another look tomorrow. 

Thanks for pointing me in the right direction :smile_cat:

**Comment by sgoudie** [comment]
Hi @tomwasd,

I'm getting the same issue. Not rendering in Facebook.

My tags are set as I can see them when I inspect the head (in production as well as development). I've added spiderable and gadicohen:phantomjs.

Is there anything else I need to do?

Thanks for creating this package!

**Comment by tomwasd** [comment]
Hi @sgoudie, are the tags present when you load the URL + '?_escaped_fragment_=' at the end?

That's what facebook tags onto the end of the URL to render the HTML

**Comment by sgoudie** [comment]
No it doesn't. Is there something I'm missing? Here's an example link. You can see the tags in the <head> http://app.doopoll.co/loop/u6CCCeMinKzPFuAhA

**Comment by tomwasd** [comment]
HI @sgoudie it looks like you haven't got spiderable and phantomjs setup properly. When it's working properly and you go to a URL with '?escaped_fragment=' on the end and view the source of the page (rather than inspecting the elements in Chrome) you should see HTML. Unfortunately on your site you see all the javascript files which then create the HTML.

**Comment by ruler88** [comment]
Hi, I was having a similar problem, I realized that I wasn't reading my server logs
I was getting a _spiderable: phantomjs failed:_ error, the follow post solved my problem:

https://github.com/meteor/meteor/issues/2429
